In [5]:
import numpy as np

In [ ]:
### Create array of favorite numbers & all 5 Functions

In [19]:
myFavorites = np.array ([5, 10, 4, 44, 8])

In [21]:
myFavorites.max()

44

In [13]:
myFavorites.min()

4

In [14]:
myFavorites.mean()

14.2

In [15]:
myFavorites.std()

15.051910177781425

In [16]:
myFavorites.sum()

71

In [ ]:
### Create array with only Ones

In [17]:
OneArrayToRuleThemAll = np.array ([1, 1, 1, 1, 1])

In [22]:
OneArrayToRuleThemAll + myFavorites

array([ 6, 11,  5, 45,  9])

In [23]:
myFavorites * 4

array([ 20,  40,  16, 176,  32])

In [24]:
myFavorites [2]

4

In [ ]:
### Create matrix

In [26]:
TheMatrixHasYou = np.array ([[3,9], 
                             [6,2]])

In [27]:
TheMatrixHasYou [0,0]

3

In [28]:
TheMatrixHasYou.max (axis=1)

array([9, 6])

In [29]:
TheMatrixHasYou.reshape (1,4)

array([[3, 9, 6, 2]])